const avatars = {
  '1': require('@Assets/images/avatars/1.png'),
  '2': require('@Assets/images/avatars/2.png'),
  '3': require('@Assets/images/avatars/3.png'),
  '4': require('@Assets/images/avatars/4.png'),
  '5': require('@Assets/images/avatars/5.png'),
  '6': require('@Assets/images/avatars/6.png'),
  '7': require('@Assets/images/avatars/7.png'),
  '8': require('@Assets/images/avatars/8.png'),
  '9': require('@Assets/images/avatars/9.png'),
  '10': require('@Assets/images/avatars/10.png'),
  '11': require('@Assets/images/avatars/11.png'),
  '12': require('@Assets/images/avatars/12.png'),
  '13': require('@Assets/images/avatars/13.png'),
  '14': require('@Assets/images/avatars/14.png'),
  '15': require('@Assets/images/avatars/15.png'),
  '16': require('@Assets/images/avatars/16.png'),
  '17': require('@Assets/images/avatars/17.png'),
  '18': require('@Assets/images/avatars/18.png'),
  '19': require('@Assets/images/avatars/19.png'),
  '21': require('@Assets/images/avatars/20.png'),
  '22': require('@Assets/images/avatars/22.png'),
  '23': require('@Assets/images/avatars/23.png'),
  '24': require('@Assets/images/avatars/24.png'),
  '25': require('@Assets/images/avatars/25.png'),
  '26': require('@Assets/images/avatars/26.png'),
  '27': require('@Assets/images/avatars/27.png'),
  '28': require('@Assets/images/avatars/28.png'),
  '29': require('@Assets/images/avatars/29.png'),
  '30': require('@Assets/images/avatars/30.png'),
};

export default avatars;
