AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: trigger when a custom reward is buy on twitch

Parameters:
  apiSecret:
    Type: String
  webhookSecret:
    Type: String

Outputs:
  TwitchCustomRewardWebhookURL:
    Description: 'API Prod stage endpoint'
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
  HandleBuyCustomReward:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: build/src/handlers/HandleBuyCustomReward.handleBuyCustomReward
      Runtime: nodejs14.x
      Description: Twitch custom reward webhook
      MemorySize: 128
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          API_SECRET: !Ref apiSecret
          WEBHOOK_SECRET: !Ref webhookSecret
